# конфигурационный файл с настройками для Spring Boot, которые подтягиваются автоматически

cxf:
  path: /bank-services/api
  jaxrs:
    component-scan: true

spring:
  jpa:
    hibernate.ddl-auto: none
    properties.hibernate:
      show_sql: true
      format_sql: true
  datasource.platform: h2
  flyway:
    baseline-on-migrate: true

swagger.suffix: services