INSERT INTO CONTACT (CONTACT_ID) values (1);
INSERT INTO CONTACT (CONTACT_ID) values (2);
INSERT INTO CONTACT (CONTACT_ID) values (3);

INSERT INTO APPLICATION (CONTACT_ID, PRODUCT_NAME, DT_CREATED) VALUES (1, 'Кредит', '2008-08-08 20:08:08');
INSERT INTO APPLICATION (CONTACT_ID, PRODUCT_NAME, DT_CREATED) VALUES (2, 'Вклад', '2008-08-08 20:08:08');